apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kunobi-pool-operator
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: kunobi-k8se2e
  path: ./deploy/flux
  prune: true
  targetNamespace: kunobi-pool
