{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kunobi-pool-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
