apiVersion: v1
kind: Service
metadata:
  name: {{ include "kobe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kobe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "kobe.selectorLabels" . | nindent 4 }}
