{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kobe.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kobe.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "kobe.selectorLabels" . | nindent 6 }}
{{- end }}
